export enum TypeNames {
  HANDLE_CHANGE_THEME_PROPERTYIES = 'HANDLE_CHANGE_THEME_PROPERTYIES',
  HANDLE_CHANGE_CURSOR_COLOR = 'HANDLE_CHANGE_CURSOR_COLOR',
  HANDLE_CHANGE_STATUSES = 'HANDLE_CHANGE_STATUSES',
  HANDLE_CHANGE_LOADING_PROPERYIES = 'HANDLE_CHANGE_LOADING_PROPERYIES',
  HANDLE_CHANGE_TEXTURE_MAPS = 'HANDLE_CHANGE_TEXTURE_MAPS',
}
